export interface Country {
  code: string;
  name: string;
  region: string;
}

// List of countries that are not blacklisted and are commonly used for professional services
export const countries: Country[] = [
  // North America
  { code: "US", name: "United States", region: "North America" },
  { code: "CA", name: "Canada", region: "North America" },
  { code: "MX", name: "Mexico", region: "North America" },
  
  // Europe
  { code: "GB", name: "United Kingdom", region: "Europe" },
  { code: "DE", name: "Germany", region: "Europe" },
  { code: "FR", name: "France", region: "Europe" },
  { code: "IT", name: "Italy", region: "Europe" },
  { code: "ES", name: "Spain", region: "Europe" },
  { code: "NL", name: "Netherlands", region: "Europe" },
  { code: "BE", name: "Belgium", region: "Europe" },
  { code: "CH", name: "Switzerland", region: "Europe" },
  { code: "AT", name: "Austria", region: "Europe" },
  { code: "SE", name: "Sweden", region: "Europe" },
  { code: "NO", name: "Norway", region: "Europe" },
  { code: "DK", name: "Denmark", region: "Europe" },
  { code: "FI", name: "Finland", region: "Europe" },
  { code: "IE", name: "Ireland", region: "Europe" },
  { code: "PT", name: "Portugal", region: "Europe" },
  { code: "PL", name: "Poland", region: "Europe" },
  { code: "CZ", name: "Czech Republic", region: "Europe" },
  { code: "HU", name: "Hungary", region: "Europe" },
  { code: "RO", name: "Romania", region: "Europe" },
  { code: "BG", name: "Bulgaria", region: "Europe" },
  { code: "HR", name: "Croatia", region: "Europe" },
  { code: "SI", name: "Slovenia", region: "Europe" },
  { code: "SK", name: "Slovakia", region: "Europe" },
  { code: "LT", name: "Lithuania", region: "Europe" },
  { code: "LV", name: "Latvia", region: "Europe" },
  { code: "EE", name: "Estonia", region: "Europe" },
  { code: "GR", name: "Greece", region: "Europe" },
  { code: "CY", name: "Cyprus", region: "Europe" },
  { code: "MT", name: "Malta", region: "Europe" },
  { code: "LU", name: "Luxembourg", region: "Europe" },
  { code: "IS", name: "Iceland", region: "Europe" },
  
  // Asia Pacific
  { code: "AU", name: "Australia", region: "Asia Pacific" },
  { code: "NZ", name: "New Zealand", region: "Asia Pacific" },
  { code: "JP", name: "Japan", region: "Asia Pacific" },
  { code: "KR", name: "South Korea", region: "Asia Pacific" },
  { code: "SG", name: "Singapore", region: "Asia Pacific" },
  { code: "HK", name: "Hong Kong", region: "Asia Pacific" },
  { code: "TW", name: "Taiwan", region: "Asia Pacific" },
  { code: "MY", name: "Malaysia", region: "Asia Pacific" },
  { code: "TH", name: "Thailand", region: "Asia Pacific" },
  { code: "PH", name: "Philippines", region: "Asia Pacific" },
  { code: "ID", name: "Indonesia", region: "Asia Pacific" },
  { code: "VN", name: "Vietnam", region: "Asia Pacific" },
  { code: "IN", name: "India", region: "Asia Pacific" },
  { code: "BD", name: "Bangladesh", region: "Asia Pacific" },
  { code: "PK", name: "Pakistan", region: "Asia Pacific" },
  { code: "LK", name: "Sri Lanka", region: "Asia Pacific" },
  { code: "NP", name: "Nepal", region: "Asia Pacific" },
  { code: "BT", name: "Bhutan", region: "Asia Pacific" },
  { code: "MV", name: "Maldives", region: "Asia Pacific" },
  { code: "MM", name: "Myanmar", region: "Asia Pacific" },
  { code: "KH", name: "Cambodia", region: "Asia Pacific" },
  { code: "LA", name: "Laos", region: "Asia Pacific" },
  { code: "BN", name: "Brunei", region: "Asia Pacific" },
  { code: "FJ", name: "Fiji", region: "Asia Pacific" },
  { code: "PG", name: "Papua New Guinea", region: "Asia Pacific" },
  { code: "SB", name: "Solomon Islands", region: "Asia Pacific" },
  { code: "VU", name: "Vanuatu", region: "Asia Pacific" },
  { code: "NC", name: "New Caledonia", region: "Asia Pacific" },
  { code: "PF", name: "French Polynesia", region: "Asia Pacific" },
  
  // Africa
  { code: "ZA", name: "South Africa", region: "Africa" },
  { code: "NG", name: "Nigeria", region: "Africa" },
  { code: "KE", name: "Kenya", region: "Africa" },
  { code: "GH", name: "Ghana", region: "Africa" },
  { code: "EG", name: "Egypt", region: "Africa" },
  { code: "MA", name: "Morocco", region: "Africa" },
  { code: "TN", name: "Tunisia", region: "Africa" },
  { code: "DZ", name: "Algeria", region: "Africa" },
  { code: "LY", name: "Libya", region: "Africa" },
  { code: "SD", name: "Sudan", region: "Africa" },
  { code: "ET", name: "Ethiopia", region: "Africa" },
  { code: "UG", name: "Uganda", region: "Africa" },
  { code: "TZ", name: "Tanzania", region: "Africa" },
  { code: "RW", name: "Rwanda", region: "Africa" },
  { code: "BI", name: "Burundi", region: "Africa" },
  { code: "DJ", name: "Djibouti", region: "Africa" },
  { code: "SO", name: "Somalia", region: "Africa" },
  { code: "ER", name: "Eritrea", region: "Africa" },
  { code: "SS", name: "South Sudan", region: "Africa" },
  { code: "CF", name: "Central African Republic", region: "Africa" },
  { code: "TD", name: "Chad", region: "Africa" },
  { code: "NE", name: "Niger", region: "Africa" },
  { code: "ML", name: "Mali", region: "Africa" },
  { code: "BF", name: "Burkina Faso", region: "Africa" },
  { code: "CI", name: "Côte d'Ivoire", region: "Africa" },
  { code: "LR", name: "Liberia", region: "Africa" },
  { code: "SL", name: "Sierra Leone", region: "Africa" },
  { code: "GN", name: "Guinea", region: "Africa" },
  { code: "GW", name: "Guinea-Bissau", region: "Africa" },
  { code: "GM", name: "Gambia", region: "Africa" },
  { code: "SN", name: "Senegal", region: "Africa" },
  { code: "MR", name: "Mauritania", region: "Africa" },
  { code: "CV", name: "Cape Verde", region: "Africa" },
  { code: "ST", name: "São Tomé and Príncipe", region: "Africa" },
  { code: "GQ", name: "Equatorial Guinea", region: "Africa" },
  { code: "GA", name: "Gabon", region: "Africa" },
  { code: "CG", name: "Republic of the Congo", region: "Africa" },
  { code: "CD", name: "Democratic Republic of the Congo", region: "Africa" },
  { code: "AO", name: "Angola", region: "Africa" },
  { code: "ZM", name: "Zambia", region: "Africa" },
  { code: "ZW", name: "Zimbabwe", region: "Africa" },
  { code: "BW", name: "Botswana", region: "Africa" },
  { code: "NA", name: "Namibia", region: "Africa" },
  { code: "SZ", name: "Eswatini", region: "Africa" },
  { code: "LS", name: "Lesotho", region: "Africa" },
  { code: "MG", name: "Madagascar", region: "Africa" },
  { code: "MU", name: "Mauritius", region: "Africa" },
  { code: "SC", name: "Seychelles", region: "Africa" },
  { code: "KM", name: "Comoros", region: "Africa" },
  { code: "YT", name: "Mayotte", region: "Africa" },
  { code: "RE", name: "Réunion", region: "Africa" },
  { code: "MZ", name: "Mozambique", region: "Africa" },
  { code: "MW", name: "Malawi", region: "Africa" },
  { code: "MG", name: "Madagascar", region: "Africa" },
  
  // South America
  { code: "BR", name: "Brazil", region: "South America" },
  { code: "AR", name: "Argentina", region: "South America" },
  { code: "CL", name: "Chile", region: "South America" },
  { code: "CO", name: "Colombia", region: "South America" },
  { code: "PE", name: "Peru", region: "South America" },
  { code: "VE", name: "Venezuela", region: "South America" },
  { code: "EC", name: "Ecuador", region: "South America" },
  { code: "BO", name: "Bolivia", region: "South America" },
  { code: "PY", name: "Paraguay", region: "South America" },
  { code: "UY", name: "Uruguay", region: "South America" },
  { code: "GY", name: "Guyana", region: "South America" },
  { code: "SR", name: "Suriname", region: "South America" },
  { code: "GF", name: "French Guiana", region: "South America" },
  
  // Central America & Caribbean
  { code: "GT", name: "Guatemala", region: "Central America" },
  { code: "BZ", name: "Belize", region: "Central America" },
  { code: "SV", name: "El Salvador", region: "Central America" },
  { code: "HN", name: "Honduras", region: "Central America" },
  { code: "NI", name: "Nicaragua", region: "Central America" },
  { code: "CR", name: "Costa Rica", region: "Central America" },
  { code: "PA", name: "Panama", region: "Central America" },
  { code: "CU", name: "Cuba", region: "Caribbean" },
  { code: "JM", name: "Jamaica", region: "Caribbean" },
  { code: "HT", name: "Haiti", region: "Caribbean" },
  { code: "DO", name: "Dominican Republic", region: "Caribbean" },
  { code: "PR", name: "Puerto Rico", region: "Caribbean" },
  { code: "TT", name: "Trinidad and Tobago", region: "Caribbean" },
  { code: "BB", name: "Barbados", region: "Caribbean" },
  { code: "AG", name: "Antigua and Barbuda", region: "Caribbean" },
  { code: "BS", name: "Bahamas", region: "Caribbean" },
  { code: "BZ", name: "Belize", region: "Caribbean" },
  { code: "DM", name: "Dominica", region: "Caribbean" },
  { code: "GD", name: "Grenada", region: "Caribbean" },
  { code: "KN", name: "Saint Kitts and Nevis", region: "Caribbean" },
  { code: "LC", name: "Saint Lucia", region: "Caribbean" },
  { code: "VC", name: "Saint Vincent and the Grenadines", region: "Caribbean" },
  
  // Middle East
  { code: "IL", name: "Israel", region: "Middle East" },
  { code: "AE", name: "United Arab Emirates", region: "Middle East" },
  { code: "SA", name: "Saudi Arabia", region: "Middle East" },
  { code: "QA", name: "Qatar", region: "Middle East" },
  { code: "KW", name: "Kuwait", region: "Middle East" },
  { code: "BH", name: "Bahrain", region: "Middle East" },
  { code: "OM", name: "Oman", region: "Middle East" },
  { code: "YE", name: "Yemen", region: "Middle East" },
  { code: "JO", name: "Jordan", region: "Middle East" },
  { code: "LB", name: "Lebanon", region: "Middle East" },
  { code: "SY", name: "Syria", region: "Middle East" },
  { code: "IQ", name: "Iraq", region: "Middle East" },
  { code: "IR", name: "Iran", region: "Middle East" },
  { code: "TR", name: "Turkey", region: "Middle East" },
  { code: "CY", name: "Cyprus", region: "Middle East" },
  
  // Other regions
  { code: "RU", name: "Russia", region: "Europe/Asia" },
  { code: "KZ", name: "Kazakhstan", region: "Central Asia" },
  { code: "UZ", name: "Uzbekistan", region: "Central Asia" },
  { code: "TM", name: "Turkmenistan", region: "Central Asia" },
  { code: "TJ", name: "Tajikistan", region: "Central Asia" },
  { code: "KG", name: "Kyrgyzstan", region: "Central Asia" },
  { code: "MN", name: "Mongolia", region: "East Asia" },
  { code: "CN", name: "China", region: "East Asia" },
  { code: "KP", name: "North Korea", region: "East Asia" },
  { code: "MM", name: "Myanmar", region: "Southeast Asia" },
  { code: "TH", name: "Thailand", region: "Southeast Asia" },
  { code: "LA", name: "Laos", region: "Southeast Asia" },
  { code: "KH", name: "Cambodia", region: "Southeast Asia" },
  { code: "VN", name: "Vietnam", region: "Southeast Asia" },
  { code: "MY", name: "Malaysia", region: "Southeast Asia" },
  { code: "SG", name: "Singapore", region: "Southeast Asia" },
  { code: "BN", name: "Brunei", region: "Southeast Asia" },
  { code: "ID", name: "Indonesia", region: "Southeast Asia" },
  { code: "TL", name: "East Timor", region: "Southeast Asia" },
  { code: "PH", name: "Philippines", region: "Southeast Asia" },
];

// Helper function to get countries by region
export const getCountriesByRegion = (region: string): Country[] => {
  return countries.filter(country => country.region === region);
};

// Helper function to get all regions
export const getRegions = (): string[] => {
  return [...new Set(countries.map(country => country.region))].sort();
};

// Helper function to search countries
export const searchCountries = (query: string): Country[] => {
  const lowercaseQuery = query.toLowerCase();
  return countries.filter(country => 
    country.name.toLowerCase().includes(lowercaseQuery) ||
    country.code.toLowerCase().includes(lowercaseQuery)
  );
};
