// Currency mapping based on country
export const COUNTRY_CURRENCIES: Record<string, { code: string; symbol: string; name: string }> = {
  // Africa
  'Nigeria': { code: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
  'South Africa': { code: 'ZAR', symbol: 'R', name: 'South African Rand' },
  'Kenya': { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling' },
  'Ghana': { code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi' },
  'Egypt': { code: 'EGP', symbol: '£', name: 'Egyptian Pound' },
  'Morocco': { code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham' },
  'Tunisia': { code: 'TND', symbol: 'د.ت', name: 'Tunisian Dinar' },
  'Algeria': { code: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar' },
  'Ethiopia': { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr' },
  'Uganda': { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling' },
  'Tanzania': { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling' },
  'Rwanda': { code: 'RWF', symbol: 'RF', name: 'Rwandan Franc' },
  'Senegal': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  'Ivory Coast': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  'Mali': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  'Burkina Faso': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  'Niger': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  'Guinea': { code: 'GNF', symbol: 'FG', name: 'Guinean Franc' },
  'Sierra Leone': { code: 'SLL', symbol: 'Le', name: 'Sierra Leonean Leone' },
  'Liberia': { code: 'LRD', symbol: 'L$', name: 'Liberian Dollar' },
  'Cameroon': { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc' },
  'Central African Republic': { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc' },
  'Chad': { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc' },
  'Congo': { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc' },
  'Equatorial Guinea': { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc' },
  'Gabon': { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc' },
  'Angola': { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza' },
  'Mozambique': { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical' },
  'Zambia': { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha' },
  'Zimbabwe': { code: 'ZWL', symbol: 'Z$', name: 'Zimbabwean Dollar' },
  'Botswana': { code: 'BWP', symbol: 'P', name: 'Botswana Pula' },
  'Namibia': { code: 'NAD', symbol: 'N$', name: 'Namibian Dollar' },
  'Lesotho': { code: 'LSL', symbol: 'L', name: 'Lesotho Loti' },
  'Swaziland': { code: 'SZL', symbol: 'E', name: 'Swazi Lilangeni' },
  'Madagascar': { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary' },
  'Mauritius': { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee' },
  'Seychelles': { code: 'SCR', symbol: '₨', name: 'Seychellois Rupee' },
  'Comoros': { code: 'KMF', symbol: 'CF', name: 'Comorian Franc' },
  'Djibouti': { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc' },
  'Eritrea': { code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa' },
  'Somalia': { code: 'SOS', symbol: 'S', name: 'Somali Shilling' },
  'Sudan': { code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound' },
  'South Sudan': { code: 'SSP', symbol: '£', name: 'South Sudanese Pound' },
  'Libya': { code: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar' },
  'Mauritania': { code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya' },
  'Cape Verde': { code: 'CVE', symbol: '$', name: 'Cape Verdean Escudo' },
  'São Tomé and Príncipe': { code: 'STN', symbol: 'Db', name: 'São Tomé and Príncipe Dobra' },
  'Guinea-Bissau': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  'Gambia': { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi' },
  'Benin': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  'Togo': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },

  // North America
  'United States': { code: 'USD', symbol: '$', name: 'US Dollar' },
  'Canada': { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
  'Mexico': { code: 'MXN', symbol: '$', name: 'Mexican Peso' },
  'Guatemala': { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal' },
  'Honduras': { code: 'HNL', symbol: 'L', name: 'Honduran Lempira' },
  'El Salvador': { code: 'USD', symbol: '$', name: 'US Dollar' },
  'Nicaragua': { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba' },
  'Costa Rica': { code: 'CRC', symbol: '₡', name: 'Costa Rican Colón' },
  'Panama': { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa' },
  'Cuba': { code: 'CUP', symbol: '$', name: 'Cuban Peso' },
  'Jamaica': { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar' },
  'Haiti': { code: 'HTG', symbol: 'G', name: 'Haitian Gourde' },
  'Dominican Republic': { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso' },
  'Puerto Rico': { code: 'USD', symbol: '$', name: 'US Dollar' },
  'Trinidad and Tobago': { code: 'TTD', symbol: 'TT$', name: 'Trinidad and Tobago Dollar' },
  'Barbados': { code: 'BBD', symbol: 'Bds$', name: 'Barbadian Dollar' },
  'Bahamas': { code: 'BSD', symbol: 'B$', name: 'Bahamian Dollar' },
  'Belize': { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar' },

  // South America
  'Brazil': { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  'Argentina': { code: 'ARS', symbol: '$', name: 'Argentine Peso' },
  'Chile': { code: 'CLP', symbol: '$', name: 'Chilean Peso' },
  'Colombia': { code: 'COP', symbol: '$', name: 'Colombian Peso' },
  'Peru': { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol' },
  'Venezuela': { code: 'VES', symbol: 'Bs.S', name: 'Venezuelan Bolívar' },
  'Ecuador': { code: 'USD', symbol: '$', name: 'US Dollar' },
  'Bolivia': { code: 'BOB', symbol: 'Bs', name: 'Bolivian Boliviano' },
  'Paraguay': { code: 'PYG', symbol: '₲', name: 'Paraguayan Guarani' },
  'Uruguay': { code: 'UYU', symbol: '$U', name: 'Uruguayan Peso' },
  'Guyana': { code: 'GYD', symbol: 'G$', name: 'Guyanese Dollar' },
  'Suriname': { code: 'SRD', symbol: '$', name: 'Surinamese Dollar' },
  'French Guiana': { code: 'EUR', symbol: '€', name: 'Euro' },

  // Europe
  'United Kingdom': { code: 'GBP', symbol: '£', name: 'British Pound' },
  'Germany': { code: 'EUR', symbol: '€', name: 'Euro' },
  'France': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Italy': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Spain': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Netherlands': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Belgium': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Austria': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Switzerland': { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc' },
  'Sweden': { code: 'SEK', symbol: 'kr', name: 'Swedish Krona' },
  'Norway': { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone' },
  'Denmark': { code: 'DKK', symbol: 'kr', name: 'Danish Krone' },
  'Finland': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Poland': { code: 'PLN', symbol: 'zł', name: 'Polish Złoty' },
  'Czech Republic': { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna' },
  'Hungary': { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint' },
  'Romania': { code: 'RON', symbol: 'lei', name: 'Romanian Leu' },
  'Bulgaria': { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev' },
  'Croatia': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Slovenia': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Slovakia': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Estonia': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Latvia': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Lithuania': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Ireland': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Portugal': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Greece': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Cyprus': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Malta': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Luxembourg': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Iceland': { code: 'ISK', symbol: 'kr', name: 'Icelandic Króna' },
  'Russia': { code: 'RUB', symbol: '₽', name: 'Russian Ruble' },
  'Ukraine': { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia' },
  'Belarus': { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble' },
  'Moldova': { code: 'MDL', symbol: 'L', name: 'Moldovan Leu' },
  'Albania': { code: 'ALL', symbol: 'L', name: 'Albanian Lek' },
  'North Macedonia': { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar' },
  'Serbia': { code: 'RSD', symbol: 'дин', name: 'Serbian Dinar' },
  'Montenegro': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Bosnia and Herzegovina': { code: 'BAM', symbol: 'КМ', name: 'Bosnia and Herzegovina Convertible Mark' },
  'Kosovo': { code: 'EUR', symbol: '€', name: 'Euro' },

  // Asia
  'China': { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  'Japan': { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  'South Korea': { code: 'KRW', symbol: '₩', name: 'South Korean Won' },
  'India': { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  'Indonesia': { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
  'Thailand': { code: 'THB', symbol: '฿', name: 'Thai Baht' },
  'Vietnam': { code: 'VND', symbol: '₫', name: 'Vietnamese Dong' },
  'Philippines': { code: 'PHP', symbol: '₱', name: 'Philippine Peso' },
  'Malaysia': { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  'Singapore': { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  'Hong Kong': { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar' },
  'Taiwan': { code: 'TWD', symbol: 'NT$', name: 'Taiwan Dollar' },
  'Pakistan': { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee' },
  'Bangladesh': { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
  'Sri Lanka': { code: 'LKR', symbol: '₨', name: 'Sri Lankan Rupee' },
  'Nepal': { code: 'NPR', symbol: '₨', name: 'Nepalese Rupee' },
  'Bhutan': { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum' },
  'Maldives': { code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa' },
  'Myanmar': { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat' },
  'Cambodia': { code: 'KHR', symbol: '៛', name: 'Cambodian Riel' },
  'Laos': { code: 'LAK', symbol: '₭', name: 'Lao Kip' },
  'Brunei': { code: 'BND', symbol: 'B$', name: 'Brunei Dollar' },
  'Mongolia': { code: 'MNT', symbol: '₮', name: 'Mongolian Tugrik' },
  'Kazakhstan': { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge' },
  'Uzbekistan': { code: 'UZS', symbol: 'лв', name: 'Uzbekistani Som' },
  'Kyrgyzstan': { code: 'KGS', symbol: 'лв', name: 'Kyrgyzstani Som' },
  'Tajikistan': { code: 'TJS', symbol: 'SM', name: 'Tajikistani Somoni' },
  'Turkmenistan': { code: 'TMT', symbol: 'T', name: 'Turkmenistani Manat' },
  'Afghanistan': { code: 'AFN', symbol: '؋', name: 'Afghan Afghani' },
  'Iran': { code: 'IRR', symbol: '﷼', name: 'Iranian Rial' },
  'Iraq': { code: 'IQD', symbol: 'د.ع', name: 'Iraqi Dinar' },
  'Syria': { code: 'SYP', symbol: '£', name: 'Syrian Pound' },
  'Lebanon': { code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound' },
  'Jordan': { code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar' },
  'Israel': { code: 'ILS', symbol: '₪', name: 'Israeli Shekel' },
  'Palestine': { code: 'ILS', symbol: '₪', name: 'Israeli Shekel' },
  'Saudi Arabia': { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal' },
  'United Arab Emirates': { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
  'Qatar': { code: 'QAR', symbol: '﷼', name: 'Qatari Riyal' },
  'Kuwait': { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar' },
  'Bahrain': { code: 'BHD', symbol: 'د.ب', name: 'Bahraini Dinar' },
  'Oman': { code: 'OMR', symbol: '﷼', name: 'Omani Rial' },
  'Yemen': { code: 'YER', symbol: '﷼', name: 'Yemeni Rial' },

  // Oceania
  'Australia': { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  'New Zealand': { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
  'Fiji': { code: 'FJD', symbol: 'FJ$', name: 'Fijian Dollar' },
  'Papua New Guinea': { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina' },
  'Solomon Islands': { code: 'SBD', symbol: 'SI$', name: 'Solomon Islands Dollar' },
  'Vanuatu': { code: 'VUV', symbol: 'Vt', name: 'Vanuatu Vatu' },
  'Samoa': { code: 'WST', symbol: 'WS$', name: 'Samoan Tala' },
  'Tonga': { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga' },
  'Kiribati': { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  'Tuvalu': { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  'Nauru': { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  'Palau': { code: 'USD', symbol: '$', name: 'US Dollar' },
  'Marshall Islands': { code: 'USD', symbol: '$', name: 'US Dollar' },
  'Micronesia': { code: 'USD', symbol: '$', name: 'US Dollar' },
  'Cook Islands': { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
  'Niue': { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
  'Tokelau': { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
  'French Polynesia': { code: 'XPF', symbol: '₣', name: 'CFP Franc' },
  'New Caledonia': { code: 'XPF', symbol: '₣', name: 'CFP Franc' },
  'Wallis and Futuna': { code: 'XPF', symbol: '₣', name: 'CFP Franc' },
};

// Get currency info for a country
export function getCurrencyForCountry(country: string): { code: string; symbol: string; name: string } {
  if (!country || typeof country !== 'string') {
    return { code: 'USD', symbol: '$', name: 'US Dollar' };
  }
  return COUNTRY_CURRENCIES[country] || { code: 'USD', symbol: '$', name: 'US Dollar' };
}

// Format currency amount
export function formatCurrency(amount: number, country: string): string {
  if (typeof amount !== 'number' || isNaN(amount)) {
    return '$0';
  }
  const currency = getCurrencyForCountry(country);
  return `${currency.symbol}${amount.toLocaleString()}`;
}

// Get currency symbol for a country
export function getCurrencySymbol(country: string): string {
  return getCurrencyForCountry(country).symbol;
}

// Get currency code for a country
export function getCurrencyCode(country: string): string {
  return getCurrencyForCountry(country).code;
}
